### ISSUE TITLE
Support for Ubuntu 20.10 

### ISSUE THREAD

**Issue by goestomars** [thiggy01/ubuntu-20.XX-change-gdm-background#17]
Hey guys, some support for Ubuntu 20.10 would be awesome.

**Comment by kazik56** [comment]
I use Pop!_OS 20.10 but since it's Ubuntu-based the process should be the same. What worked for me was changing `focal` to `groovy` in line 13.

**Comment by thiggy01** [comment]
Just added support for Ubuntu 20.10!
